### ISSUE TITLE
Error loading library: No module named 'lib.google_search_results'

### ISSUE THREAD

**Issue by ioanf2** [serpapi/google-search-results-python#23] opened 2021-06-29 13:02 UTC
Error loading library: No module named 'lib.google_search_results'

Check this:

https://snipboard.io/

**Comment by jvmvik** [comment] 2021-07-26 02:23
what version of python are you using?

**Comment by jvmvik** [comment] 2021-07-26 17:01
closing because cannot reproduce on the CI server or locally.
please upgrade to Python 3.5 as described in the documentation.

**Closed by jvmvik** 2021-07-26 17:01 UTC
